export interface ObjectCode {
  code: string;
  description: string;
}

export interface ObjectCodeFlag {
  id: string;
  label: string;
  objectCodes: string[];
  objectCode: true;
}

export const OBJECT_CODE_FLAG_PREFIX = "object:";

export function objectCodeFlagId(code: string): string {
  return `${OBJECT_CODE_FLAG_PREFIX}${code}`;
}

export function objectCodeFromFlagId(id: string | null | undefined): ObjectCode | null {
  if (!id || !id.startsWith(OBJECT_CODE_FLAG_PREFIX)) return null;
  const code = id.slice(OBJECT_CODE_FLAG_PREFIX.length);
  return OBJECT_CODES.find((item) => item.code === code) || null;
}

export const OBJECT_CODES: ObjectCode[] = [
  { code: "0100", description: "REPAIR FRONT AXLE AND SUSPENSION AS NEEDED" },
  { code: "0101", description: "REPAIR FRONT AIR BAGS AS NEEDED" },
  { code: "0102", description: "REPAIR LEVELING VALVE FRONT AS NEEDED" },
  { code: "0103", description: "REPAIR BEARINGS, SEALS AS NEEDED" },
  { code: "0104", description: "REPAIR KING PINS AS NEEDED" },
  { code: "0105", description: "REPAIR RADIUS RODS, BUSHING & LINK AS NEEDED" },
  { code: "0106", description: "REPAIR SHOCKS AND BUSHINGS AS NEEDED" },
  { code: "0107", description: "REPAIR KNEELERS AS NEEDED" },
  { code: "0109", description: "REPAIR FRONT LEAF/ TORSION SPRING AS NEEDED" },
  { code: "0175", description: "CHANGE FRONT HUB FLUID" },
  { code: "0200", description: "REPAIR STEERING AS NEEDED" },
  { code: "0201", description: "REPAIR STABILIZER BARS, BUSHINGS, PANHARD ROD AS NEEDED" },
  { code: "0202", description: "REPAIR DRAG LINK/ TIE ROD ENDS AS NEEDED" },
  { code: "0203", description: "REPAIR POWER STEERING GEAR ASSEMBLY AS NEEDED" },
  { code: "0204", description: "REPAIR POWER STEERING LINES, FITTINGS AS NEEDED" },
  { code: "0205", description: "REPAIR POWER STEERING PUMP AS NEEDED" },
  { code: "0206", description: "REPAIR STEERING BOX- WHEEL ALIGNMENT AS NEEDED" },
  { code: "0207", description: "REPAIR STEERING WHEEL AS NEEDED" },
  { code: "0209", description: "REPAIR POWER STEERING PUMP AS NEEDED" },
  { code: "0210", description: "REPAIR STEERING SHAFT/U-JOINTS AS NEEDED" },
  { code: "0300", description: "REPAIR REAR AXLE AND SUSPENSION AS NEEDED" },
  { code: "0301", description: "REPAIR REAR AIR BAGS AS NEEDED" },
  { code: "0302", description: "REPAIR LEVELING VALVE LEFT REAR" },
  { code: "0303", description: "REPAIR LEVELING VALVE, RIGHT REAR" },
  { code: "0304", description: "REPAIR RADIUS ROD BUSHING, LINK AND PANHARD ROD AS NEEDED" },
  { code: "0305", description: "REPAIR SHOCKS AND BUSHINGS AS NEEDED" },
  { code: "0306", description: "REPAIR STABILIZER BAR, BUSHINGS AS NEEDED" },
  { code: "0307", description: "REPAIR REAR LEAF/ TORSION SPRING AS NEEDED" },
  { code: "0308", description: "REPAIR DIFFERENTIAL REPLACEMENT AS NEEDED" },
  { code: "0309", description: "REPAIR BEARINGS/ SEALS AS NEEDED" },
  { code: "0375", description: "CHANGE DIFFERENTIAL FLUID" },
  { code: "0400", description: "REPAIR BRAKES AS NEEDED" },
  { code: "0401", description: "REPAIR CAMSHAFT AS NEEDED" },
  { code: "0402", description: "REPAIR BRAKE DRUMS AS NEEDED" },
  { code: "0403", description: "REPAIR FRONT BRAKE CHAMBER AS NEEDED" },
  { code: "0404", description: "REPAIR FRONT BRAKE JOB AS NEEDED" },
  { code: "0405", description: "REPAIR BRAKE LININGS AS NEEDED" },
  { code: "0406", description: "REPAIR PARKING BRAKE AS NEEDED" },
  { code: "0407", description: "REPAIR REAR BRAKE JOB AS NEEDED" },
  { code: "0408", description: "REPAIR REAR BRAKE CHAMBER AS NEEDED" },
  { code: "0409", description: "REPAIR BRAKE SHOES AS NEEDED" },
  { code: "0410", description: "REPAIR SLACK ADJUSTERS AS NEEDED" },
  { code: "0411", description: "REPAIR BRAKE VALVES AS NEEDED" },
  { code: "0412", description: "REPAIR BRAKE INTERLOCK AS NEEDED" },
  { code: "0413", description: "REPAIR ABS REPAIRS CODES, ECU R&R, SENSORS AS NEEDED" },
  { code: "0414", description: "REPAIR TAG AXLE BRAKE JOB AS NEEDED" },
  { code: "0415", description: "BRAKE TEST AS NEEDED" },
  { code: "0416", description: "REPAIR E-STROKE SYSTEM" },
  { code: "0600", description: "REPAIR COOLING SYSTEM AS NEEDED" },
  { code: "0601", description: "ANTIFREEZE CHECK AS NEEDED" },
  { code: "0602", description: "REPAIR FAN DRIVE AND VALVE AS NEEDED" },
  { code: "0603", description: "REPAIR BLOCK HEATER AND CORD AS NEEDED" },
  { code: "0604", description: "REPAIR HOSES, LINES AS NEEDED" },
  { code: "0605", description: "REPAIR RADIATOR REPLACEMENT AS NEEDED" },
  { code: "0606", description: "REPAIR SURGE TANK AS NEEDED" },
  { code: "0607", description: "REPAIR THERMOSTATS AS NEEDED" },
  { code: "0608", description: "REPAIR WATER PUMP AS NEEDED" },
  { code: "0609", description: "ADD GLYCOL AS NEEDED" },
  { code: "0610", description: "REPAIR SHUT OFF VALVES AS NEEDED" },
  { code: "0611", description: "REPAIR WEBASTO/PRO-HEAT SYSTEM COMPONENTS AS NEEDED" },
  { code: "0613", description: "REPAIR GLYCOL LEAK AS NEEDED" },
  { code: "0700", description: "REPAIR ELECTRICAL AND LIGHTING AS NEEDED" },
  { code: "0701", description: "REPAIR ALARM AND WARNING DEVICE AS NEEDED" },
  { code: "0702", description: "REPAIR ALTERNATOR, CHARGING SYSTEM AS NEEDED" },
  { code: "0703", description: "REPAIR BATTERY CABLES AS NEEDED" },
  { code: "0704", description: "REPAIR BREAKERS AND FUSES AS NEEDED" },
  { code: "0705", description: "REPAIR TURN SIGNAL SWITCH AS NEEDED" },
  { code: "0706", description: "REPAIR EXTERIOR LIGHTS AS NEEDED" },
  { code: "0707", description: "REPAIR HORN AS NEEDED" },
  { code: "0708", description: "REPAIR INSTRUMENT PANEL AS NEEDED" },
  { code: "0709", description: "REPAIR INTERIOR LIGHTS AS NEEDED" },
  { code: "0710", description: "REPAIR RELAYS AS NEEDED" },
  { code: "0711", description: "REPAIR STARTER AS NEEDED" },
  { code: "0712", description: "REPAIR SWITCHES AS NEEDED" },
  { code: "0713", description: "REPAIR WIRING AS NEEDED" },
  { code: "0714", description: "BATTERY REPLACEMENT AS NEEDED" },
  { code: "0715", description: "REPAIR EQUALIZER AS NEEDED" },
  { code: "0716", description: "REPAIR MULTIPLEX SYSTEM AS NEEDED" },
  { code: "0717", description: "REPAIR COMPARTMENT LIGHTS AS NEEDED" },
  { code: "0800", description: "REPAIR ENGINE AS NEEDED" },
  { code: "0801", description: "REPAIR OIL LINES, HOSES AS NEEDED" },
  { code: "0802", description: "REPAIR ENGINE OIL LEAK AS NEEDED" },
  { code: "0803", description: "REPAIR OIL COOLER AS NEEDED" },
  { code: "0804", description: "REPAIR TURBOCHARGER AS NEEDED" },
  { code: "0805", description: "REPAIR INJECTOR AND RACK AS NEEDED" },
  { code: "0806", description: "REPAIR ENGINE TUNE UP AS NEEDED" },
  { code: "0807", description: "REPAIR ENGINE MONITORING SYSTEMS AS NEEDED" },
  { code: "0808", description: "ENGINE REPLACEMENT" },
  { code: "0809", description: "ADD ENGINE OIL AS NEEDED" },
  { code: "0810", description: "REMOVE ENGINE PACK AS NEEDED" },
  { code: "0811", description: "INSTALL ENGINE PACK AS NEEDED" },
  { code: "0812", description: "REPAIR TURBOCHARGER REPLACEMENT AS NEEDED" },
  { code: "0814", description: "REPAIR ENGINE SPINNER FILTER AS NEEDED" },
  { code: "0815", description: "REPAIR BELTS, TENSIONERS, PULLEYS AS NEEDED" },
  { code: "0818", description: "CHECK COILS REPLACE SPARK PLUGS" },
  { code: "0824", description: "CNG VALVE ADJUSTMENT" },
  { code: "0900", description: "REPAIR IGNITION SYSTEM AS NEEDED" },
  { code: "1000", description: "REPAIR EXHAUST SYSTEM AS NEEDED" },
  { code: "1001", description: "REPAIR CATALYST REPLACEMENT AS NEEDED" },
  { code: "1002", description: "REPAIR PARTICAL TRAP REPLACEMENT AS NEEDED" },
  { code: "1003", description: "REPAIR AFTER TREATMENT SYSTEM AS NEEDED" },
  { code: "1004", description: "REPAIR REGENERATION AS NEEDED" },
  { code: "1006", description: "REPAIR EGR SYSTEM AS NEEDED" },
  { code: "1007", description: "ADD DEF" },
  { code: "1100", description: "REPAIR CHARGE AIR SYSTEM AS NEEDED" },
  { code: "1101", description: "REPAIR AIR FILTER AS NEEDED" },
  { code: "1102", description: "REPAIR EXHAUST PIPES, HOSES, CLAMPS AS NEEDED" },
  { code: "1200", description: "REPAIR FUEL SYSTEM AS NEEDED" },
  { code: "1201", description: "REPAIR FUEL LINES AS NEEDED" },
  { code: "1202", description: "REPAIR FUEL PUMP AS NEEDED" },
  { code: "1203", description: "REPAIR FUEL TANK, LINES, FILLER AS NEEDED" },
  { code: "1204", description: "CNG TANK AND FUEL LINES INSPECTION" },
  { code: "1205", description: "DE-FUEL CNG TANK" },
  { code: "1236", description: "CNG TANK AND FUEL LINES INSPECTION" },
  { code: "1300", description: "REPAIR TRANSMISSION AS NEEDED" },
  { code: "1301", description: "REPAIR OIL COOLER AS NEEDED" },
  { code: "1302", description: "REPAIR OIL LINES, FITTINGS AS NEEDED" },
  { code: "1303", description: "REPAIR SHIFTER AS NEEDED" },
  { code: "1304", description: "REPAIR TRANS ASSEMBLY AS NEEDED" },
  { code: "1305", description: "REPAIR VALVE BODY/ SWITCHES AS NEEDED" },
  { code: "1306", description: "REPAIR RETARDER/ ACCUMULATOR AS NEEDED" },
  { code: "1307", description: "REPAIR TRANSMISSION MONITORING SYSTEMS AS NEEDED" },
  { code: "1308", description: "REPAIR TRANSMISSION REPLACEMENT AS NEEDED" },
  { code: "1309", description: "ADD TRANSMISSION FLUID AS NEEDED" },
  { code: "1311", description: "REPAIR TRANS. FLUID LEAK AS NEEDED" },
  { code: "1312", description: "REPAIR TRANS SEALS/ GASKETS AS NEEDED" },
  { code: "1375", description: "TRANS P.M. 75000" },
  { code: "1375 - NF XD40 2020", description: "TRANS P.M. 75000" },
  { code: "1400", description: "REPAIR DRIVESHAFT/ U-JOINTS AS NEEDED" },
  { code: "1500", description: "REPAIR BODY AND FRAME AS NEEDED" },
  { code: "1501", description: "REPAIR DOORS/ ACCESS DOORS AS NEEDED" },
  { code: "1502", description: "REPAIR BODY - FRONT AS NEEDED" },
  { code: "1503", description: "REPAIR BODY - LEFT AS NEEDED" },
  { code: "1504", description: "REPAIR DOOR PROPS AS NEEDED" },
  { code: "1505", description: "REPAIR BODY - REAR AS NEEDED" },
  { code: "1506", description: "REPAIR BODY - RIGHT SIDE AS NEEDED" },
  { code: "1507", description: "REPAIR ROOF VENTS AS NEEDED" },
  { code: "1508", description: "REPAIR STEPWELLS AS NEEDED" },
  { code: "1509", description: "REPAIR BODY TRIM AS NEEDED" },
  { code: "1510", description: "REPAIR C-FRAME AS NEEDED" },
  { code: "1511", description: "REPAIR UNDERSTRUCTURE AS NEEDED" },
  { code: "1512", description: "BODY ESTIMATE REPAIR" },
  { code: "1513", description: "REPAIR BODY REPAIR ESTIMATE AS NEEDED" },
  { code: "1555", description: "REPAIR ADVERTISEMENT WRAP AS NEEDED" },
  { code: "1600", description: "REPAIR INTERIOR AS NEEDED" },
  { code: "1601", description: "REPAIR INTERIOR SEATS AS NEEDED" },
  { code: "1602", description: "REPAIR GRABRAILS AS NEEDED" },
  { code: "1603", description: "REPAIR INTERIOR MIRROR BRACKETS AS NEEDED" },
  { code: "1604", description: "REPAIR PULL CORDS AS NEEDED" },
  { code: "1605", description: "REPAIR FLOORING AS NEEDED" },
  { code: "1606", description: "REPAIR WALL COVERINGS AS NEEDED" },
  { code: "1607", description: "REPAIR SEAT BELTS AS NEEDED" },
  { code: "1608", description: "REPAIR INTERIOR ADVERTISING AS NEEDED" },
  { code: "1609", description: "REPAIR DRIVERS SEAT AS NEEDED" },
  { code: "1610", description: "REPAIR ADA SEATING AS NEEDED" },
  { code: "1611", description: "INTERIOR CLEANING" },
  { code: "1700", description: "REPAIR GLAZING AS NEEDED" },
  { code: "1701", description: "REPAIR ALL MIRRORS/ ARMS/ SUPPORTS AS NEEDED" },
  { code: "1702", description: "REPAIR WINDOWS AS NEEDED" },
  { code: "1703", description: "REPAIR GLASS REPLACEMENT AS NEEDED" },
  { code: "1800", description: "REPAIR DOORS/ INTERLOCKS AS NEEDED" },
  { code: "1801", description: "REPAIR AIR VALVES/ DOOR CONTROLLER AS NEEDED" },
  { code: "1802", description: "REPAIR ELECTRIC, RELAY, SWITCH AS NEEDED" },
  { code: "1803", description: "REPAIR SHAFTS, BEARINGS, RODS, ENDS AS NEEDED" },
  { code: "1804", description: "REPAIR SENSITIVE EDGES, COMPONENTS AS NEEDED" },
  { code: "1900", description: "REPAIR INSTRUMENTS AND GAUGES AS NEEDED" },
  { code: "1901", description: "REPAIR HUBOMETER REPLACEMENT AS NEEDED" },
  { code: "1902", description: "REPAIR SPEEDOMETER AS NEEDED" },
  { code: "1903", description: "REPAIR DASH MODULE AS NEEDED" },
  { code: "1904", description: "REPAIR DASH GAUGES AS NEEDED" },
  { code: "1905", description: "REPAIR ENGINE GAUGES AS NEEDED" },
  { code: "1906", description: "REPAIR MISC. SENSORS AS NEEDED" },
  { code: "2000", description: "REPAIR PNEUMATIC AS NEEDED" },
  { code: "2001", description: "REPAIR AIR LINES AS NEEDED" },
  { code: "2002", description: "REPAIR TANKS AS NEEDED" },
  { code: "2003", description: "REPAIR VALVES AS NEEDED" },
  { code: "2004", description: "REPAIR AIR DRYER AS NEEDED" },
  { code: "2005", description: "REPAIR AIR COMPRESSOR AS NEEDED" },
  { code: "2006", description: "REPAIR AIR GOVERNOR AS NEEDED" },
  { code: "2007", description: "REPAIR AIR SWITCHES AS NEEDED" },
  { code: "2008", description: "REPAIR AIR, HYDRAULIC LEAKS AS NEEDED" },
  { code: "2100", description: "REPAIR AIR CONDITIONING AS NEEDED" },
  { code: "2101", description: "REPAIR ALTERNATOR AS NEEDED" },
  { code: "2102", description: "REPAIR A/C ALTERNATOR BELT AS NEEDED" },
  { code: "2103", description: "REPAIR CONDENSER MOTOR AS NEEDED" },
  { code: "2104", description: "REPAIR COMPRESSOR AS NEEDED" },
  { code: "2105", description: "REPAIR CONDENSER AS NEEDED" },
  { code: "2106", description: "REPAIR CLUTCH, SHAFT, AIR CYLINDER AS NEEDED" },
  { code: "2107", description: "REPAIR EVAPORATOR AS NEEDED" },
  { code: "2108", description: "REPAIR EXPANSION VALVE AS NEEDED" },
  { code: "2109", description: "REPAIR HOSES, PIPING AS NEEDED" },
  { code: "2110", description: "REPAIR MISC. CLIMATE CONTROL AS NEEDED" },
  { code: "2111", description: "REPAIR VOLTAGE REGULATOR AS NEEDED" },
  { code: "2112", description: "REPAIR COMPRESSOR SEAL AS NEEDED" },
  { code: "2113", description: "REPAIR SWITCH/ RELAY/ BREAKER AS NEEDED" },
  { code: "2114", description: "REPAIR CONTROLLER, CLIMATE CONTROL AS NEEDED" },
  { code: "2115", description: "A/C START-UP" },
  { code: "2116", description: "DRIER REPLACEMENT AS NEEDED" },
  { code: "2117", description: "REPAIR UV LIGHT AS NEEDED" },
  { code: "2200", description: "REPAIR HEAT AND VENTILATION SYSTEMS AS NEEDED" },
  { code: "2201", description: "REPAIR BLOWER MOTOR AS NEEDED" },
  { code: "2202", description: "REPAIR HEATER CORES AND HOSES AS NEEDED" },
  { code: "2203", description: "REPAIR MARINE PUMP AS NEEDED" },
  { code: "2205", description: "REPAIR HEATER HOSES AND CLAMPS AS NEEDED" },
  { code: "2206", description: "REPAIR HEAT VALVES & SWITCHES AS NEEDED" },
  { code: "2207", description: "PROHEAT INSPECTION" },
  { code: "2208", description: "REPAIR PROHEAT AS NEEDED" },
  { code: "2300", description: "REPAIR DEFROSTER AS NEEDED" },
  { code: "2301", description: "REPAIR DEFROSTER MOTOR AS NEEDED" },
  { code: "2302", description: "REPAIR DEFROSTER CORE AS NEEDED" },
  { code: "2303", description: "REPAIR DEFROSTER HOSES, CLAMPS AS NEEDED" },
  { code: "2304", description: "REPAIR DEFROSTER VALVES, SWITCHES AS NEEDED" },
  { code: "2400", description: "REPAIR TIRES AND WHEELS AS NEEDED" },
  { code: "2401", description: "REPAIR CATS EYE SYSTEM AS NEEDED" },
  { code: "2402", description: "RETORQUE WHEEL NUTS AS NEEDED" },
  { code: "2403", description: "PAINT WHEELS AS NEEDED" },
  { code: "2404", description: "REPAIR TIRE PRESSURE MONITOR SYSTEM AS NEEDED" },
  { code: "2405", description: "CHANGE TIRE- LOW PRESSURE" },
  { code: "2406", description: "CHANGE TIRE- TREAD DEPTH" },
  { code: "2407", description: "PERFORM WHEEL BALANCING AS NEEDED" },
  { code: "2500", description: "REPAIR LIFT SYSTEMS AS NEEDED" },
  { code: "2502", description: "REPAIR WHEELCHAIR RAMP AS NEEDED" },
  { code: "2503", description: "W/C RAMP INSPECTION" },
  { code: "2504", description: "REPAIR MOTOR/ CHAIN/ TENSIONER AS NEEDED" },
  { code: "2509", description: "REPAIR WHEELCHAIR AS NEEDED" },
  { code: "2510", description: "REPAIR WHEELCHAIR SECUREMENT DEVICES AS NEEDED" },
  { code: "2600", description: "REPAIR RADIO AS NEEDED" },
  { code: "2602", description: "I.B.S." },
  { code: "2603", description: "M.D.T." },
  { code: "2604", description: "I.V.L.U" },
  { code: "2605", description: "FILE RESTRUCTURE" },
  { code: "2606", description: "ROUTE/ ANNOUNCEMENT FILES" },
  { code: "2607", description: "REPAIR P.A. SYSTEM AS NEEDED" },
  { code: "2608", description: "REPAIR G.P.S. AS NEEDED" },
  { code: "2609", description: "REPAIR WLAN COMMUNICATION AS NEEDED" },
  { code: "2610", description: "REPAIR FAREBOX/ IBS COMMUNICATIONS AS NEEDED" },
  { code: "2611", description: "REPAIR RADIO HAND SET AS NEEDED" },
  { code: "2612", description: "INSPECT/REPAIR AUTOMATIC PASSENGER COUNTER" },
  { code: "2613", description: "REPAIR ANTENNA AS NEEDED" },
  { code: "2614", description: "REPAIR WIRING AS NEEDED" },
  { code: "2615", description: "REPAIR LOG-ON AS NEEDED" },
  { code: "2616", description: "REPAIR ODOMETER AS NEEDED" },
  { code: "2700", description: "REPAIR FAREBOXES AS NEEDED" },
  { code: "2701", description: "REPAIR DOLLAR BILL TRANSPORT AS NEEDED" },
  { code: "2702", description: "REPAIR COIN MECHANISM AS NEEDED" },
  { code: "2703", description: "REPAIR FAREBOX CASH BOX AS NEEDED" },
  { code: "2704", description: "REPAIR LED DISPLAY AS NEEDED" },
  { code: "2705", description: "REPAIR KEYBOARD AS NEEDED" },
  { code: "2706", description: "ENTIRE BOX, P.M. INSPECTION" },
  { code: "2708", description: "REPAIR REPLACE LOGIC BOARD AS NEEDED" },
  { code: "2800", description: "REPAIR DESTINATION SIGNS, ELECT, AND APCS AS NEEDED" },
  { code: "2801", description: "REPAIR VIDEO SURVEILLANCE AS NEEDED" },
  { code: "2802", description: "REPAIR RECORDERS/ DVD/ HARD DRIVE AS NEEDED" },
  { code: "2803", description: "REPAIR CAMERA HOUSINGS/ ADJUST VIEW AS NEEDED" },
  { code: "2804", description: "CAMERA SYSTEM INSPECTION" },
  { code: "2900", description: "REPAIR MISC. ACCESSORIES AS NEEDED" },
  { code: "2901", description: "REPAIR WIPERS, ARMS, IDLERS AS NEEDED" },
  { code: "2902", description: "REPAIR WASHER HOSE/ PUMP AS NEEDED" },
  { code: "2903", description: "REPAIR WIPER BLADES AS NEEDED" },
  { code: "2904", description: "REPAIR WIPER CONTROLS AS NEEDED" },
  { code: "2905", description: "REPAIR BICYCLE RACK AS NEEDED" },
  { code: "2906", description: "REPAIR AUDIBLE ALERT AS NEEDED" },
  { code: "3100", description: "REPAIR P.A. SYSTEM AS NEEDED" },
  { code: "3101", description: "REPAIR VENTRA SYSTEM AS NEEDED" },
  { code: "3102", description: "VENTRA MOBILE VALIDATOR" },
  { code: "3103", description: "VENTRA DRIVER'S TERMINAL" },
  { code: "3104", description: "VENTRA PRINTED CIRCUIT BOARD" },
  { code: "3105", description: "VENTRA WIRING" },
  { code: "3200", description: "REPAIR HYDRAULIC SYSTEM AS NEEDED" },
  { code: "3201", description: "REPAIR HYDRAULIC TANK AS NEEDED" },
  { code: "3202", description: "CHANGE HYDRAULIC FLUID" },
  { code: "3204", description: "REPAIR HYDRAULIC CONTROLS AS NEEDED" },
  { code: "3205", description: "REPAIR HYDRAULIC FAN DRIVE AS NEEDED" },
  { code: "3206", description: "REPAIR HYDRAULIC PUMP AS NEEDED" },
  { code: "3207", description: "ADD HYDRAULIC FLUID AS NEEDED" },
  { code: "3208", description: "REPAIR HYDRAULIC LINES AS NEEDED" },
  { code: "3209", description: "REPAIR HYDRAULIC VALVES AS NEEDED" },
  { code: "5000", description: "ROADCALL- ACCIDENT AS NEEDED" },
  { code: "5001", description: "ROADCALL- FRONT AXLE/ SUSPENSION AS NEEDED" },
  { code: "5002", description: "ROADCALL- STEERING AS NEEDED" },
  { code: "5003", description: "ROADCALL- REAR AXLE/ SUSPENSION AS NEEDED" },
  { code: "5004", description: "ROADCALL- BRAKES AS NEEDED" },
  { code: "5005", description: "ROADCALL- CLUTCH AS NEEDED" },
  { code: "5006", description: "ROADCALL- COOLING SYSTEM AS NEEDED" },
  { code: "5007", description: "ROADCALL- ELECTRICAL/ LIGHTING AS NEEDED" },
  { code: "5008", description: "ROADCALL- ENGINE AS NEEDED" },
  { code: "5010", description: "ROADCALL- EXHAUST AS NEEDED" },
  { code: "5011", description: "ROADCALL- BLOWER/ AIR INDUCTION AS NEEDED" },
  { code: "5012", description: "ROADCALL- FUEL SYSTEM AS NEEDED" },
  { code: "5013", description: "ROADCALL- TRANSMISSION AS NEEDED" },
  { code: "5014", description: "ROADCALL- PROPELLER SHAFTS AS NEEDED" },
  { code: "5015", description: "ROADCALL- BODY & FRAME AS NEEDED" },
  { code: "5016", description: "ROADCALL- INTERIOR AS NEEDED" },
  { code: "5017", description: "ROADCALL- GLAZING AS NEEDED" },
  { code: "5018", description: "ROADCALL- DOORS/ INTERLOCKS AS NEEDED" },
  { code: "5019", description: "ROADCALL- INSTRUMENTS/ GAUGES AS NEEDED" },
  { code: "5020", description: "ROADCALL- PNEUMATIC AS NEEDED" },
  { code: "5021", description: "ROADCALL- AIR CONDITIONING AS NEEDED" },
  { code: "5022", description: "ROADCALL- HEATER/ VENT SYSTEM AS NEEDED" },
  { code: "5023", description: "ROADCALL- DEFROSTER AS NEEDED" },
  { code: "5024", description: "ROADCALL- TIRES/ WHEELS AS NEEDED" },
  { code: "5025", description: "ROADCALL- LIFT SYSTEMS AS NEEDED" },
  { code: "5026", description: "ROADCALL- RADIOS AS NEEDED" },
  { code: "5027", description: "ROADCALL- FAREBOXES AS NEEDED" },
  { code: "5028", description: "ROADCALL- DESTINATION SIGNS AS NEEDED" },
  { code: "5029", description: "ROADCALL- MISC. ACCESSORIES AS NEEDED" },
  { code: "5031", description: "Road call ventra system" },
  { code: "5032", description: "ROAD CALL REPAIR HYDRAULIC SYSTEM AS NEEDED" },
  { code: "5064", description: "Road Call Fire Suppression System" },
  { code: "6400", description: "FIRE SUPPRESSION SYSTEM INSP" },
  { code: "6401", description: "REPAIR FIRE SUPPRESSOR REPAIR AS NEEDED" },
  { code: "6402", description: "REPAIR FIRE SUPPRESSION TANK AS NEEDED" },
  { code: "6403", description: "REPAIR FIRE SUPPRESSION CONTROLS AS NEEDED" },
  { code: "6404", description: "FIRE SUPPRESSION 6 YR INSP." },
  { code: "6405", description: "FIRE SUPPRESSION 12 YR INSP." },
  { code: "6406", description: "METHANE DETECTION SYSTEM INSPECTION" },
  { code: "6500", description: "IDOT INSPECTION/ SAFETY STICKER" },
  { code: "6603", description: "PM-A 3000 MILES" },
  { code: "6603 - ENC 30FT AXESS 2020", description: "PM-A 3000 MILES" },
  { code: "6603 - NF XD40 2020", description: "PM-A 3000 MILES" },
  { code: "6609", description: "PM-A 9000 MILES" },
  { code: "6609 - ENC 30FT AXESS 2020", description: "PM-A 9000 MILES" },
  { code: "6609 - NF XD40 2020", description: "PM-A 9000 MILES" },
  { code: "6615", description: "PM-A 15000 MILES" },
  { code: "6615 - ENC 30FT AXESS 2020", description: "PM-A 15000 MILES" },
  { code: "6615 - NF XD40 2020", description: "PM-A 15000 MILES" },
  { code: "6621", description: "PM-A 21000 MILES" },
  { code: "6621 - ENC 30FT AXESS 2020", description: "PM-A 21000 MILES" },
  { code: "6621 - NF XD40 2020", description: "PM-A 21000 MILES" },
  { code: "6706", description: "PM-B 6000 MILES" },
  { code: "6706 - ENC 30FT AXESS 2020", description: "PM-B 6000 MILES" },
  { code: "6706 - NF XD40 2020", description: "PM-B 6000 MILES" },
  { code: "6712", description: "PM-B 12000 MILES" },
  { code: "6712 - ENC 30FT AXESS 2020", description: "PM-B 12000 MILES" },
  { code: "6712 - NF XD40 2020", description: "PM-B 12000 MILES" },
  { code: "6718", description: "PM-B 18000 MILES" },
  { code: "6718 - ENC 30FT AXESS 2020", description: "PM-B 18000 MILES" },
  { code: "6718 - NF XD40 2020", description: "PM-B 18000 MILES" },
  { code: "6800", description: "PM-C 24000 MILES" },
  { code: "6800 - ENC 30FT AXESS 2020", description: "PM-C 24000 MILES" },
  { code: "6800 - NF XD40 2020", description: "PM-C 24000 MILES" },
  { code: "6901", description: "PARATRANSIT PM-A" },
  { code: "6902", description: "PARATRANSIT PM-B" },
  { code: "6903", description: "PARATRANSIT PM-C" },
  { code: "6905", description: "PM-3000 MILE COMMUNITY VAN INSPECTION" },
  { code: "7000", description: "REPAIR BUILDINGS AND GROUNDS AS NEEDED" },
  { code: "7001", description: "SNOW REMOVAL" },
  { code: "7002", description: "ELECTRICAL MAINT/ REPAIR" },
  { code: "7003", description: "PNEUMATIC MAINT/ REPAIR" },
  { code: "7004", description: "HYDRAULIC MAINT/ REPAIR" },
  { code: "7005", description: "HVAC MAINT/ REPAIR" },
  { code: "7006", description: "FUELING SYSTEM MAINT/ REPAIR" },
  { code: "7007", description: "BUSWASH MAINT/ REPAIR" },
  { code: "7100", description: "TRAINING/ FORMAL INSTRUCTION" },
  { code: "7200", description: "SUPERVISION/ FOREMAN/ ACTING FOREMAN AS NEEDED" },
  { code: "7300", description: "FUELING/ REVENUE/ NON-REVENUE VEHICLES AS NEEDED" },
  { code: "7400", description: "WASHING/ ALL PURPOSE CLEANING AS NEEDED" },
  { code: "7500", description: "EQUIPMENT REPAIR/ SHOP/ NON REVENUE AS NEEDED" },
  { code: "7600", description: "CUSTODIAL/ HOUSEKEEPING AS NEEDED" },
  { code: "7700", description: "DELIVERY- PICKUP BUS" },
  { code: "7800", description: "REPAIR BUILDING MAINTENANCE AS NEEDED" },
  { code: "7900", description: "PARTS CHASING AS NEEDED" },
  { code: "8000", description: "REPAIR BUSES, REGULAR AS NEEDED" },
  { code: "8100", description: "REPAIR BUSES, PARATRANSIT AS NEEDED" },
  { code: "8200", description: "REPAIR VEHICLES, NON-REVENUE AS NEEDED" },
  { code: "9100", description: "CHEMICALS, COMPOUNDS, PAINT AS NEEDED" },
  { code: "9200", description: "SAFETY AND MEDICAL AS NEEDED" },
  { code: "9300", description: "REPAIR HAND TOOLS AS NEEDED" },
  { code: "9400", description: "REPAIR POWER TOOLS AS NEEDED" },
  { code: "9500", description: "COMMON USE MATERIAL" },
  { code: "9999", description: "Health and Safety Campaign" },
];

export function objectCodeLabel(code: string): string {
  const item = OBJECT_CODES.find((c) => c.code === code);
  return item ? `${item.code} ${item.description}` : code;
}

export const OBJECT_CODE_FLAGS: ObjectCodeFlag[] = OBJECT_CODES.map((item) => ({
  id: objectCodeFlagId(item.code),
  label: item.code,
  objectCodes: [item.code],
  objectCode: true,
}));
